name: Lint Build pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  EVENT_NAME: ${{ github.event_name }}
  SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
  SECRET: ${{ secrets.SECRET }}
  
jobs:
  build_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001
      - name: slack notification on build failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took

  deploy_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: deploy to heroku
        id: deploy
        if: env.EVENT_NAME == 'push' && env.SKIP == 'false'
        uses: akhileshns/heroku-deploy@v3.10.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mooc-bloglist"
          heroku_email: "iko.hyppanen@gmail.com"
          remote_branch: main
          healthcheck: "https://mooc-bloglist.herokuapp.com/api/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true0
      - name: slack notification on deploy success
        env:
          DEPLOY_SUCCESS: ${{ steps.deploy.outcome }}
        if: ${{ env.DEPLOY_SUCCESS == 'success' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `a new version deployed to https://mooc-bloglist.herokuapp.com/ (${process.env.AS_COMMIT})\nby ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`
              }]
            }
  
  tagging_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        env:
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: 0.1.0
          PRERELEASE_SUFFIX: 'tag'
          DRY_RUN: false
        if: env.EVENT_NAME == 'push' && env.SKIP == 'false'
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598